# Site settings
title: "360TFT - Master The Game"
description: "Transform average players into match-winners with proven football coaching methodologies. 15+ years experience, 1000+ coaches trained worldwide."
url: "https://360tft.co.uk"
baseurl: ""

# Author information
author:
  name: "Kevin Middleton"
  email: "kevin@360tft.com"
  twitter: "coach_kevin_m"

# SEO settings
lang: en-GB
timezone: Europe/London

# Social media
social:
  twitter: "coach_kevin_m"
  youtube: "@360TFT"
  linkedin: "kevinmiddleton360"
  instagram: "360tft"

# Build settings (GitHub Pages compatible)
markdown: kramdown
highlighter: rouge
permalink: pretty

# SASS configuration
sass:
  style: compressed

# Plugins (GitHub Pages whitelist only)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.py"
  - "*.json"
  - "*.bat"
  - requirements.txt
  - automation_*.json
  - automation_*.py
  - Quality_Control_System.py
  - Subagent_Orchestrator.py
  - Topic_Selection_Manager.py
  - Weekly_Content_Automation.py
  - initialize_automation.py
  - test_integration.py
  - orchestrator_config.json
  - automation_config.json
  - automation_schedule.json
  - content_templates.json
  - quality_standards.json
  - temp_css_review.md
  - AUTOMATION_*.md
  - IMPLEMENTATION_SUMMARY.md
  - CSS_ARCHITECTURE_*.md
  - GAME_MODEL_CSS_*.md
  - MISSING_CSS_*.md
  - ORPHANED_FILES_*.md
  - QUICK_START.md

# Site constants for reuse
site_constants:
  brand_color: "#976bdd"
  accent_color: "#ff5757"
  years_experience: "15+"
  coaches_mentored: "1200+"
  players_developed: "1000+"
  sessions_created: "800+"
  community_size: "1200+"
  
# Product pricing (CORRECT DOLLAR PRICING)
pricing:
  complete_system:
    current: "$127"
    old: "$305"
    payments: "4 payments of $31.75"
    currency_symbol: "$"
  game_model:
    current: "$40"
    regular: "$80"
    savings: "$40"
    currency_symbol: "$"
  sessions_328:
    current: "$34.20"
    old: "$42.00"
    discount_code: "10"
    currency_symbol: "$"
  coaches_compass:
    current: "FREE"
    old: ""
    currency_symbol: ""
  uefa_c:
    current: "$20"
    old: ""
    currency_symbol: "$"
  tgfp:
    current: "$20"
    old: "$35"
    currency_symbol: "$"
  cheatsheet_vault:
    current: "$10"
    old: "$15"
    currency_symbol: "$"
  academy:
    current_monthly: "$15"
    current_yearly: "$99"
    future_monthly: "$20"
    future_yearly: "$150"
    currency_symbol: "$"
    price_increase_date: "01/09/2025"

# Purchase links (VERIFIED URLs)
purchase_links:
  complete_system: "https://360tft.com/l/CompleteCoachingMasterySystem"
  game_model: "https://360tft.com/l/360TFTGM"
  sessions_328: "https://360tft.com/l/TrainingSessionsForAllAges"
  coaches_compass: "https://360tft.com/l/TheCoachCompass"
  uefa_c: "https://360tft.com/l/svnymr"
  tgfp: "https://360tft.com/l/tgfp"
  cheatsheet_vault: "https://360tft.com/l/CoachingCheatsheetVault"
  academy: "https://www.skool.com/coachingacademy"
  
# Contact information
contact:
  email: "support@360tft.com"
  academy_email: "academy@360tft.com"
  phone: "+44 (0) 123 456 7890"