# Additional Performance Configuration
# Include this in your main _config.yml or use as reference

# Advanced Jekyll Build Optimizations
profile: false
trace: false
verbose: false
full_rebuild: false

# Liquid performance settings
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: true

# Plugin performance configurations
jekyll-minifier:
  preserve_php: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  compress_json: true
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false

# Responsive image settings (detailed)
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 85
  sizes:
    - width: 320
      quality: 80
    - width: 480
      quality: 82
    - width: 768
      quality: 85
    - width: 1024
      quality: 85
    - width: 1200
      quality: 90
  extra_images:
    - assets/images/*.{gif,jpg,jpeg,png}
  strip: true
  cache: true
  output_path_format: assets/images/resized/%{dirname}/%{basename}-%{width}.%{extension}
  save_to_source: false

# SEO tag optimizations
seo_tag:
  image: /assets/images/360tft-social-share.jpg
  type: website

# Feed optimizations
feed:
  collections:
    posts:
      path: "/feed.xml"
  excerpt_only: false
  posts_limit: 20

# Archive optimizations
jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    category: '/category/:name/'
    tag: '/tag/:name/'