# Site settings
title: "360TFT - Master The Game"
description: "Transform average players into match-winners with proven football coaching methodologies. 15+ years experience, 1000+ coaches trained worldwide."
url: "https://360tft.co.uk"
baseurl: ""

# Author information
author:
  name: "Kevin Middleton"
  email: "kevin@360tft.com"
  twitter: "coach_kevin_m"

# SEO settings
lang: en-GB
timezone: Europe/London

# Social media
social:
  twitter: "coach_kevin_m"
  youtube: "@360TFT"
  linkedin: "kevinmiddleton360"
  instagram: "360tft"

# Navigation menu (UPDATED TO INCLUDE GAME MODEL)
navigation:
  - title: "Home"
    url: "/"
  - title: "About Kevin"
    url: "/about-kevin-middleton/"
  - title: "Game Model"
    url: "/game-model/"
  - title: "328 Sessions"
    url: "/328-sessions/"
  - title: "Coach's Compass"
    url: "/coaches-compass/"
  - title: "Academy"
    url: "/football-coaching-academy/"
  - title: "Success Stories"
    url: "/testimonials/"

# Footer links
footer_links:
  - title: "Training Resources"
    links:
      - title: "328 Training Sessions"
        url: "/328-sessions/"
      - title: "360TFT Game Model"
        url: "/game-model/"
      - title: "Coach's Compass"
        url: "/coaches-compass/"
      - title: "Coaching Cheatsheets"
        url: "/coaching-cheatsheet-vault/"
      - title: "Grassroots Pack"
        url: "/tgfp/"
  - title: "Community"
    links:
      - title: "Football Coaching Academy"
        url: "/football-coaching-academy/"
      - title: "Success Stories"
        url: "/testimonials/"
      - title: "Contact"
        url: "/contact/"
  - title: "About Kevin"
    links:
      - title: "Biography"
        url: "/about-kevin-middleton/"
      - title: "Coaching Philosophy"
        url: "/about-kevin-middleton/#philosophy"
  - title: "Support"
    links:
      - title: "Contact Us"
        url: "/contact/"
      - title: "Help Center"
        url: "/help/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# SASS configuration (GitHub Pages compatible)
sass:
  sass_dir: _sass
  style: compressed

# Plugins (GitHub Pages whitelist only)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
    - width: 1024
    - width: 1200
  strip: true
  quality: 85
  output_path_format: assets/images/resized/%{dirname}/%{basename}-%{width}.%{extension}

# Jekyll compress images
compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

# Minification settings
jekyll-minifier:
  preserve_php: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  compress_json: true
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false

# Archives configuration for better content organization
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Pagination settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Exclude files from build (performance optimization)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - gulpfile.js
  - webpack.config.js
  - .sass-cache
  - .jekyll-cache
  - .git
  - .gitignore
  - "*.tmp"
  - "*.backup"

# Collections for blog posts (if needed later)
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Site constants for reuse
site_constants:
  brand_color: "#976bdd"
  accent_color: "#ff5757"
  years_experience: "15+"
  coaches_mentored: "1200+"
  players_developed: "5000+"
  sessions_created: "328"
  community_size: "1200+"
  
# Product pricing (CORRECT DOLLAR PRICING)
pricing:
  complete_system:
    current: "$127"
    old: "$305"
    payments: "4 payments of $31.75"
    currency_symbol: "$"
  game_model:
    current: "$20"
    regular: "$40"
    savings: "$20"
    currency_symbol: "$"
  sessions_328:
    current: "$34.20"
    old: "$42.00"
    discount_code: "10"
    currency_symbol: "$"
  coaches_compass:
    current: "FREE"
    old: ""
    currency_symbol: ""
  uefa_c:
    current: "$20"
    old: ""
    currency_symbol: "$"
  tgfp:
    current: "$20"
    old: "$35"
    currency_symbol: "$"
  cheatsheet_vault:
    current: "$10"
    old: "$15"
    currency_symbol: "$"
  academy:
    current_monthly: "$47"
    current_yearly: "$499"
    future_monthly: "$67"
    future_yearly: "$699"
    currency_symbol: "$"
    price_increase_date: "01/08/2025"

# Purchase links (VERIFIED URLs)
purchase_links:
  complete_system: "https://360tft.com/l/CompleteCoachingMasterySystem"
  game_model: "https://360tft.com/l/360TFTGM"
  sessions_328: "https://360tft.com/l/TrainingSessionsForAllAges"
  coaches_compass: "https://360tft.com/l/TheCoachCompass"
  uefa_c: "https://360tft.com/l/svnymr"
  tgfp: "https://360tft.com/l/tgfp"
  cheatsheet_vault: "https://360tft.com/l/CoachingCheatsheetVault"
  academy: "https://www.skool.com/coachingacademy"
  
# Contact information
contact:
  email: "support@360tft.com"
  academy_email: "academy@360tft.com"
  phone: "+44 (0) 123 456 7890"
  
# Analytics (add your tracking IDs)
google_analytics: "G-XXXXXXXXXX"
facebook_pixel: "XXXXXXXXXX"

# SEO Enhanced Configuration
seo:
  type: Organization
  name: "360TFT"
  logo: "/assets/images/logo-360tft.jpg"

# Feed configuration (enhanced)
feed:
  posts_limit: 20
  excerpt_only: false

# Sitemap configuration (enhanced)
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
    - "/search.html"
    - "/admin/"

# Performance monitoring
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Jekyll performance optimizations
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Additional build optimizations
strict_front_matter: true
show_drafts: false
limit_posts: 0
lsi: false
excerpt_separator: "\n\n"
incremental: true

# Cache settings for faster builds
cache_dir: .jekyll-cache