# Site settings
title: "360TFT - Master The Game"
description: "Transform average players into match-winners with proven football coaching methodologies. 15+ years experience, 1000+ coaches trained worldwide."
url: "https://360tft.github.io"
baseurl: "/360tft"

# Author information
author:
  name: "Kevin Middleton"
  email: "kevin@360tft.com"
  twitter: "coach_kevin_m"

# SEO settings
lang: en-GB
timezone: Europe/London

# Social media
social:
  twitter: "coach_kevin_m"
  youtube: "@360TFT"
  linkedin: "kevinmiddleton360"
  instagram: "360tft"

# Navigation menu
navigation:
  - title: "Home"
    url: "/"
  - title: "Complete System"
    url: "/complete-coaching-mastery-system"
  - title: "328 Sessions"
    url: "/328-football-training-sessions"
  - title: "Coach's Compass"
    url: "/coaches-compass"
  - title: "Academy"
    url: "/football-coaching-academy"
  - title: "About Kevin"
    url: "/about-kevin-middleton"

# Footer links
footer_links:
  - title: "Training Resources"
    links:
      - title: "328 Training Sessions"
        url: "/328-football-training-sessions"
      - title: "360TFT Game Model"
        url: "/360tft-game-model"
      - title: "Coach's Compass"
        url: "/coaches-compass"
      - title: "Coaching Cheatsheets"
        url: "/coaching-cheatsheet-vault"
      - title: "Grassroots Pack"
        url: "/grassroots-football-pack"
  - title: "Community"
    links:
      - title: "Free Community"
        url: "https://www.skool.com/360tft-6754"
      - title: "Coaching Academy"
        url: "https://www.skool.com/coachingacademy"
      - title: "Weekly Masterclasses"
        url: "/academy#masterclasses"
      - title: "Success Stories"
        url: "/success-stories"
  - title: "About Kevin"
    links:
      - title: "Biography"
        url: "/about-kevin-middleton"
      - title: "Coaching Philosophy"
        url: "/about-kevin-middleton#philosophy"
      - title: "Testimonials"
        url: "/testimonials"
      - title: "Speaking"
        url: "/speaking"
  - title: "Support"
    links:
      - title: "Contact Us"
        url: "/contact"
      - title: "FAQ"
        url: "/faq"
      - title: "Help Center"
        url: "/help"
      - title: "Refund Policy"
        url: "/refund-policy"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections for blog posts (if needed later)
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Site constants for reuse
site_constants:
  brand_color: "#976bdd"
  accent_color: "#ff5757"
  years_experience: "15+"
  coaches_mentored: "1000+"
  players_developed: "5000+"
  sessions_created: "328"
  
# Contact information
contact:
  email: "support@360tft.com"
  academy_email: "academy@360tft.com"
  phone: "+44 (0) 123 456 7890"
  
# Analytics (add your tracking IDs)
google_analytics: "G-XXXXXXXXXX"
facebook_pixel: "XXXXXXXXXX"

# SEO
seo:
  type: Organization
  name: "360TFT"
  logo: "/assets/images/logo-360tft.jpg"